# Generated by Django 6.0.6 on 2026-06-08 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ao3_id', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('fandoms', models.JSONField(default=list)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('warnings', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('characters', models.JSONField(default=list)),
                ('relationships', models.JSONField(default=list)),
                ('additional_tags', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('total_chapters', models.IntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(blank=True, null=True)),
                ('kudos', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('bookmarks', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reread_count', models.IntegerField(default=0)),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fics', to='fics.fic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fic')},
            },
        ),
        migrations.AddField(
            model_name='fic',
            name='users',
            field=models.ManyToManyField(related_name='fics', through='fics.UserFic', to=settings.AUTH_USER_MODEL),
        ),
    ]
